georgipav

on:
  push:
    branches:
      - main

jobs:
  backend_tests_with_ruff:
    name: Tests backend
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: foodgram_user
          POSTGRES_PASSWORD: foodgram_password
          POSTGRES_DB: foodgram_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.8.0
          pip install -r ./backend/requirements.txt

      - name: test with ruff
        run: python -m ruff check backend/

      - name: test backend
        env:
          POSTGRES_USER: foodgram_user
          POSTGRES_PASSWORD: foodgram_password
          POSTGRES_DB: foodgram_db
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
        run: |
          cd backend/
          python manage.py test

  build_and_push_backend_to_dockerhub:
    name: Build backend Docker image and push to DockerHub
    runs-on: ubuntu-latest
    needs: backend_tests_with_ruff
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up Docker
        uses: docker/setup-buildx-action@v3
      - name: login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./backend/
          push: true
          tags: georgipav/foodgram_backend:latest

  build_and_push_frontend_to_dockerhub:
    name: Build frontend Docker image and push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup Docker
        uses: docker/setup-buildx-action@v3
      - name: login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/
          push: true
          tags: georgipav/foodgram_frontend:latest

  send_message:
    name: Send message via TG bot when finished
    runs-on: ubuntu-latest
    needs:
      - build_and_push_backend_to_dockerhub
      - build_and_push_frontend_to_dockerhub
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Образы foodgram успешно загружены!